name: "Build Document by osdg"
description: "Build Document by openapi-static-document-generator"
inputs:
  repo:
    description: openapi document repository
    required: true
  repo-token:
    description: Personal Access Token for accessing a private repository
    required: false
  build-path:
    required: false
    default: "./out"
    description: path to output directory
  cli-url:
    description: url to cli tool binary
    required: false
    default: "https://github.com/usbharu/openapi-static-document-generator/releases/download/v0.1.0/cli"
  fron-ref:
    description: fromend repository ref
    required: false
runs:
  using: composite

  steps:
    - name: checkout generator
      uses: actions/checkout@v4
      with:
        repository: usbharu/openapi-static-document-generator
        ref: ${{ inputs.fron-ref }}
    - name: setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Setup Pages
      uses: actions/configure-pages@v4
      with:
          # Automatically inject basePath in your Next.js configuration file and disable
          # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
          #
          # You may remove this line if you want to manage the configuration yourself.
          static_site_generator: next
          generator_config_file: ./site/next.config.mjs
    - name: Download cli
      run: wget ${{ inputs.cli-url }} -O osdg
      shell: bash
    - run: chmod +x osdg
      shell: bash
    - name: download spec
      run: ./osdg download -u ${{ inputs.repo }} -o docs
      shell: bash
    - name: generate diff
      run: ./osdg diff -i docs
      shell: bash
    - name: generate spec
      run: ./osdg generate -i docs -o site
      shell: bash
    - name: Download Dependency
      working-directory: site
      run: npm ci
      shell: bash
    - name: Download Dependency
      working-directory: site
      run: npm run build
      shell: bash
